name: Lint

on:
  push:
    branches:
      - master
    paths:
      - dist/

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/setup-go@master
      with:
        go-version: "1.13.3"
    - name: Plugin Lint
      run: |
        git clone https://github.com/grafana/plugin-validator;
        cd ./plugin-validator/cmd/plugincheck;
        go install
        cd ../../;
        plugincheck -url https://github.com/yesoreyeram/grafana-servicenow-datasource;
        exit $?;